eye = input('Please enter a character for the eye:')
print("##########")
print("#  ", eye, eye ," #")
print("#        #")
print("##########")
print("    ##    ")
print("    ##    ")
print("##  ##  ##")
print("#   ##   #")
print("#   ##   # # OK")
print("    ##    ")
print(" #  ##  # ")
print(" #      # ")
print(" #      # ")
print(" #      # ")

print()

eye = input('Please enter a character for the eye:')
smile = input('Please input a character for the smile:')
print("##########")
print("#  {} ".format(eye) ,"{}  #".format(eye) )
print("# {}".format(smile) ,"{}".format(smile),"{}  #".format(smile))
print("##########")
print("    ##    ")
print("    ##    ")
print("##  ##  ##")
print("#   ##   #")
print("#   ##   # # OK")
print("    ##    ")
print(" #  ##  # ")
print(" #      # ")
print(" #      # ")
print(" #      # ")

print()